import type { Metadata } from 'next';
import { Noto_Serif_Bengali } from 'next/font/google';
import Marquee from '@/components/Marquee';
import './globals.css';
import Header from '@/components/Header';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/footer';

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ['latin', 'bengali'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Marquee></Marquee>
        <main className="max-w-7xl mx-auto">{children}</main>
        <Toaster></Toaster>

        <Footer></Footer>
      </body>
    </html>
  );
}
